TiendaElectronica/TiendaElectronica/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf.urls import url
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('usuario/', include('gestion_usuarios.urls')),
    path('', include('administracion.urls'))
]

TiendaElectronica/administracion/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from . import views

app_name = 'administracion'

urlpatterns = [
    path('', views.PostListView.as_view(), name='index')
]

TiendaElectronica/gestion_usuarios/urls.py
from django.conf.urls import url
from . import views
app_name = 'gestion_usuarios'

urlpatterns = [
    url('registrar/', views.registrar, name='registrar'),
    url('login/', views.usuario_login, name='login'),
    url('logout/', views.usuario_logout, name='logout'),
]

TiendaElectronica/administracion/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Tienda(models.Model):
    nombre_tienda = models.CharField(max_length=200, unique=True)
    direccion = models.CharField(max_length=200)
    ciudad = models.CharField(max_length=200)
    comuna = models.CharField(max_length=200)
    telefono = models.IntegerField()
    email = models.EmailField()
    encargado = models.ForeignKey(User, on_delete=models.CASCADE, related_name='encargado',null=True)

    def __str__(self):
        return self.nombre_tienda

TiendaElectronica/gestion_usuarios/models.py
from django.db import models
from django.contrib.auth.models import User
from administracion.models import Tienda
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.

class VendedorUsuario(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    tienda = models.ForeignKey(Tienda, on_delete=models.CASCADE, null=True)

@receiver(post_save, sender=User)
def create_user_vendedorusuario(sender, instance, created, **kwargs):
    if created:
        VendedorUsuario.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_vendedorusuario(sender, instance, **kwargs):
    instance.vendedorusuario.save()

TiendaElectronica/gestion_usuarios/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import VendedorUsuario,Tienda

class VendedorUsuarioForm(forms.ModelForm):
    class Meta():
        model = VendedorUsuario
        fields = ('tienda',)
        labels = {
            'tienda' : 'Tienda'
        }
    def __init__(self, *args, **kwargs):
        super(VendedorUsuarioForm, self).__init__(*args,**kwargs)
        
        for field in self.fields:
            self.fields[field].widget.attrs.update({'class': 'form-control'})
            

class RegistrarForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password', 'first_name', 'last_name',)
        labels = {
            'username' : 'Nombre de usuario',
            'email' : 'Correo',
            'password': 'Contraseña',
            'first_name': 'Nombres',
            'last_name': 'Apellidos'

        }
        help_texts = {
           'username': '',
        }
        error_messages = {
            'username': {
                'max_length': 'Máximo 150 carácteres',
                'required': 'Requerido'
            },
            'password': {
                'required': 'Requerido'
            },
            'email': {
                'required': 'Requerido'
            },
            'first_name': {
                'required': 'Requerido'
            },
            'last_name': {
                'required': 'Requerido'
            },
        }
    
    def __init__(self, *args, **kwargs):
        super(RegistrarForm, self).__init__(*args, **kwargs)

        for field in self.fields:
            self.fields[field].widget.attrs.update({'class': 'form-control'})

TiendaElectronica/administracion/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from .models import Tienda
from django.utils import timezone
from django.urls import reverse
from django.views.generic import DetailView, ListView
# Create your views here.


class PostListView(ListView):
    model = Tienda
    template_name = "administracion/index.html"

TiendaElectronica/gestion_usuarios/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from .forms import RegistrarForm, VendedorUsuarioForm
# Para iniciar sesión

def usuario_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('administracion:index'))


def usuario_login(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('administracion:index'))
    else:
        if request.method == 'POST':
            username = request.POST['username']
            password = request.POST.get('password')
            user = authenticate(username=username, password=password)
            if user:
                if user.is_active:
                    login(request, user)
                    return HttpResponseRedirect(reverse('administracion:index'))
                else:
                    return HttpResponse("Tu cuenta está inactiva.")
            else:
                print("username: {} - password: {}".format(username, password))
                return HttpResponse("Datos inválidos")
        else:
            return render(request, 'gestion_usuarios/login.html', {})

def registrar(request):
    registrado = False
    if request.method == 'POST':
        user_form = RegistrarForm(data=request.POST)
        vendedorusuario_form = VendedorUsuarioForm(data=request.POST)
        if user_form.is_valid() and vendedorusuario_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()         
            vendedorusuario_form.save(commit=False)
            registrado = True
            return HttpResponseRedirect(reverse('gestion_usuarios:login'))
        else:
            print(user_form.errors, vendedorusuario_form.errors)
    else:
        user_form = RegistrarForm()
        vendedorusuario_form = VendedorUsuarioForm()

    return render(request, 'gestion_usuarios/registrar.html',
                  {'user_form': user_form,
                   'vendedorusuario_form': vendedorusuario_form,
                   'registrado': registrado})

TiendaElectronica/administracion/templates/administracion/index.html
{% extends 'master.html' %}

{% block title %}Portada{% endblock %}

{% block background %}{% load static %}{% static 'core/img/home-bg.jpg' %}{% endblock %}

{% block headers %}
<h1>Tienda Electrónica</h1>
{% comment %} <span class="subheading">Desarrollador fullstack</span> {% endcomment %}
{% endblock %}

TiendaElectronica/gestion_usuarios/templates/gestion_usuarios/login.html
{% extends 'master.html' %}
{% load static %}
{% block content %}

<div class="login">
    <h1>Iniciar Sesión</h1>
    <form method="post" >
        {% csrf_token %}
        <div class="form-group">
            <label for="username">Username:</label>
            <input type="text" class="form-control" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <label for="password">Password:</label>
            <input type="password" class="form-control" name="password" placeholder="Password">
        </div>
        <button type="submit" class="btn btn-primary">Iniciar sesión</button>
    </form>
</div>
{% endblock content %}

TiendaElectronica/gestion_usuarios/templates/gestion_usuarios/registrar.html
{% extends 'master.html' %}
{% block content %}
 <div class="jumbotron">
      {% if registrado %}
        <h1>Gracias por registrarte</h1>
      {% else %}
        <h1>Registro</h1>
        <h3>Llena los siguientes datos</h3>
        <form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ user_form.as_p }}
          {{ vendedorusuario_form.as_p }}
          <button type="submit" class="btn btn-primary">Registrar</button>
        </form>
        
      {% endif %}
    </div>
{% endblock content %}

TiendaElectronica/templates/master.html
{% load static %}
<!DOCTYPE html>
<html lang="es">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{%block title%}{% endblock %} | GARESOFT</title>

<head>
    <link href="{% static 'core/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'core/vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href="{% static 'core/css/clean-blog.min.css' %}" rel="stylesheet">
    <link href="{% static 'core/css/custom.css' %}" rel="stylesheet">
</head>

 <!-- Navegación -->
    <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
      <div class="container">
       <a class="navbar-brand" href="{% url 'administracion:index' %}">GARESOFT</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          Menú
          <i class="fa fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">      
            <li class="nav-item"><a class="nav-link" href="{% url 'administracion:index' %}">index</a></li>
            {% if not request.user.is_authenticated %}
            <li class="nav-item"><a class="nav-link" href="{% url 'gestion_usuarios:login' %}">iniciar sesión</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'gestion_usuarios:registrar' %}">registrar</a></li>
            {% else %}
            
            <li class="nav-item"><a class="nav-link" href="{% url 'gestion_usuarios:logout' %}">logout</a></li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
    
    <!-- Cabecera -->
    <header class="masthead" style="background-image: url('{% block background %}{% endblock %}')">
      <div class="overlay"></div>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <div class="site-heading">
              {% block headers %}{% endblock %}
            </div>
          </div>
        </div>
      </div>
    </header>

    {% block content %}
    {% endblock %}
    
<!-- Pié de página -->
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <ul class="list-inline text-center">
              <li class="list-inline-item">
                <a href="#">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-envelope fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-youtube fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
            </ul>
            <p class="copyright text-muted">Copyright &copy; 2020 · garesoft </p>
          </div>
        </div>
      </div>
    </footer>

    <!-- Bootstrap y Javascripts -->
    <script src="{% static 'core/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'core/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'core/js/clean-blog.min.js' %}"></script>

  </body>

</html>